-- Smart Attendance Tracker — Seed Data (IIITN CSH Branch)
-- Run after schema.sql to populate data
-- NOTE: Passwords here are placeholders. Use install.php for proper bcrypt hashes.

USE smart_attendance;

-- ============================================================
-- ADMIN (password: password123 — hash generated by install.php)
-- ============================================================
INSERT INTO admins (username, full_name, email, password) VALUES
('admin', 'System Admin', 'admin@iiitn.ac.in', '$HASH_PLACEHOLDER');

-- ============================================================
-- SUBJECTS (7 theory + 3 labs = 10)
-- ============================================================
INSERT INTO subjects (subject_code, subject_name) VALUES
('AE',     'Applied Electronics'),
('DS',     'Data Structures'),
('MTTDE',  'Matrices, Transform Techniques, and Differential Equations'),
('APG',    'Applied Physics for Gaming'),
('AP',     'Application Programming'),
('GDDT',   'Game Development and Design Thinking'),
('EVS',    'Environmental Studies'),
('AE-LAB', 'Applied Electronics Lab'),
('DS-LAB', 'Data Structures Lab'),
('AP-LAB', 'Application Programming Lab');

-- ============================================================
-- TEACHERS (7 — password: password123)
-- ============================================================
INSERT INTO teachers (teacher_code, full_name, email, password) VALUES
('TCH001', 'Dr. Shankar Bhattacharjee', 'shankar.b@iiitn.ac.in',  '$HASH_PLACEHOLDER'),
('TCH002', 'Mr. Daud Ali',              'daud.ali@iiitn.ac.in',    '$HASH_PLACEHOLDER'),
('TCH003', 'Mr. Nikhil',                'nikhil@iiitn.ac.in',      '$HASH_PLACEHOLDER'),
('TCH004', 'Ms. Akansha Goel',          'akansha.goel@iiitn.ac.in','$HASH_PLACEHOLDER'),
('TCH005', 'Dr. Aatish Daryapurkar',    'aatish.d@iiitn.ac.in',    '$HASH_PLACEHOLDER'),
('TCH006', 'Dr. Shailesh Janbandhu',    'shailesh.j@iiitn.ac.in',  '$HASH_PLACEHOLDER'),
('TCH007', 'Dr. Santosh Kumar Sahu',    'santosh.sahu@iiitn.ac.in','$HASH_PLACEHOLDER');

-- ============================================================
-- TEACHER ↔ SUBJECT (semester 2, sections A1 & A2)
-- ============================================================
INSERT INTO teacher_subjects (teacher_id, subject_id, semester, section) VALUES
-- Dr. Shankar → AE + AE Lab
(1, 1, 2, 'A1'), (1, 1, 2, 'A2'), (1, 8, 2, 'A1'), (1, 8, 2, 'A2'),
-- Mr. Daud → MTTDE
(2, 3, 2, 'A1'), (2, 3, 2, 'A2'),
-- Mr. Nikhil → GDDT
(3, 6, 2, 'A1'), (3, 6, 2, 'A2'),
-- Ms. Akansha → AP + AP Lab
(4, 5, 2, 'A1'), (4, 5, 2, 'A2'), (4, 10, 2, 'A1'), (4, 10, 2, 'A2'),
-- Dr. Aatish → APG
(5, 4, 2, 'A1'), (5, 4, 2, 'A2'),
-- Dr. Shailesh → EVS
(6, 7, 2, 'A1'), (6, 7, 2, 'A2'),
-- Dr. Santosh → DS + DS Lab
(7, 2, 2, 'A1'), (7, 2, 2, 'A2'), (7, 9, 2, 'A1'), (7, 9, 2, 'A2');

-- ============================================================
-- STUDENTS (69 — BT25CSH001 to BT25CSH069)
-- A1: 001–035, A2: 036–069
-- NOTE: Use install.php or reseed.php for proper password hashing
-- ============================================================

-- ============================================================
-- TIMETABLE (Hall 2, Semester 2 — CSH)
-- Subject IDs: 1=AE, 2=DS, 3=MTTDE, 4=APG, 5=AP, 6=GDDT, 7=EVS,
--              8=AE-LAB, 9=DS-LAB, 10=AP-LAB
-- ============================================================

-- Monday (Theory — both sections)
INSERT INTO timetable (day_name, start_time, end_time, subject_id, semester, section) VALUES
('Monday', '09:00', '10:00', 1, 2, 'A1'), ('Monday', '09:00', '10:00', 1, 2, 'A2'),
('Monday', '10:00', '11:00', 2, 2, 'A1'), ('Monday', '10:00', '11:00', 2, 2, 'A2'),
('Monday', '11:00', '12:00', 3, 2, 'A1'), ('Monday', '11:00', '12:00', 3, 2, 'A2'),
('Monday', '12:00', '13:00', 4, 2, 'A1'), ('Monday', '12:00', '13:00', 4, 2, 'A2'),
-- Monday Labs
('Monday', '15:00', '17:00', 10, 2, 'A2'), -- AP Lab (A2) Lab 2
('Monday', '15:00', '17:00',  9, 2, 'A1'), -- DS Lab (A1) Lab 6

-- Tuesday (Theory)
('Tuesday', '09:00', '10:00', 1, 2, 'A1'), ('Tuesday', '09:00', '10:00', 1, 2, 'A2'),
('Tuesday', '10:00', '11:00', 1, 2, 'A1'), ('Tuesday', '10:00', '11:00', 1, 2, 'A2'),
('Tuesday', '11:00', '12:00', 4, 2, 'A1'), ('Tuesday', '11:00', '12:00', 4, 2, 'A2'),
('Tuesday', '12:00', '13:00', 2, 2, 'A1'), ('Tuesday', '12:00', '13:00', 2, 2, 'A2'),
-- Tuesday Lab
('Tuesday', '15:00', '17:00', 10, 2, 'A1'), -- AP Lab (A1) Lab 8

-- Wednesday (Theory)
('Wednesday', '09:00', '10:00', 6, 2, 'A1'), ('Wednesday', '09:00', '10:00', 6, 2, 'A2'),
('Wednesday', '10:00', '11:00', 5, 2, 'A1'), ('Wednesday', '10:00', '11:00', 5, 2, 'A2'),
('Wednesday', '11:00', '12:00', 3, 2, 'A1'), ('Wednesday', '11:00', '12:00', 3, 2, 'A2'),
('Wednesday', '12:00', '13:00', 4, 2, 'A1'), ('Wednesday', '12:00', '13:00', 4, 2, 'A2'),
-- Wednesday Labs
('Wednesday', '14:00', '16:00', 8, 2, 'A1'), -- AE Lab (A1) Electronics Lab
('Wednesday', '16:00', '18:00', 8, 2, 'A2'), -- AE Lab (A2) Electronics Lab

-- Thursday (Theory)
('Thursday', '09:00', '10:00', 6, 2, 'A1'), ('Thursday', '09:00', '10:00', 6, 2, 'A2'),
('Thursday', '10:00', '11:00', 5, 2, 'A1'), ('Thursday', '10:00', '11:00', 5, 2, 'A2'),
('Thursday', '11:00', '12:00', 3, 2, 'A1'), ('Thursday', '11:00', '12:00', 3, 2, 'A2'),
('Thursday', '12:00', '13:00', 3, 2, 'A1'), ('Thursday', '12:00', '13:00', 3, 2, 'A2'), -- MTTDE Tute
('Thursday', '14:00', '15:00', 7, 2, 'A1'), ('Thursday', '14:00', '15:00', 7, 2, 'A2'), -- EVS

-- Friday (Theory)
('Friday', '09:00', '10:00', 3, 2, 'A1'), ('Friday', '09:00', '10:00', 3, 2, 'A2'), -- MTTDE Tute
('Friday', '10:00', '11:00', 5, 2, 'A1'), ('Friday', '10:00', '11:00', 5, 2, 'A2'),
('Friday', '11:00', '12:00', 7, 2, 'A1'), ('Friday', '11:00', '12:00', 7, 2, 'A2'),
('Friday', '12:00', '13:00', 2, 2, 'A1'), ('Friday', '12:00', '13:00', 2, 2, 'A2'),
-- Friday Lab
('Friday', '15:00', '17:00', 9, 2, 'A2'); -- DS Lab (A2) Lab 2

-- ============================================================
-- SAMPLE NOTICES
-- ============================================================
INSERT INTO notices (role_type, title, message, created_by) VALUES
('all',     'Welcome to Smart Attendance',  'The Smart Attendance Tracker is now live for CSH Semester 2. Use your IIITN credentials to log in.', 'System Admin'),
('student', 'Maintain 75% Attendance',      'All students must maintain at least 75% attendance in every subject (including labs) to be eligible for end-semester exams.', 'System Admin'),
('teacher', 'OTP Session Guide',            'OTP sessions are valid for 60 seconds. Students must enter the OTP within this window. You can also end sessions manually.', 'System Admin');
